---
- include_tasks: swap.yml
  tags: undercloud-host-setup

- include_tasks: hostname.yml
  tags: undercloud-host-setup

- include_tasks: dns.yml
  tags: undercloud-host-setup
  when: undercloud_host_setup_dns|bool
