- name: set swapfile info
  set_fact:
    swapfile_path: "{{ swapfile_location|default('/swapfile') }}"
    swapfile_size: "{{ swapfile_size_mb|default(4096) }}"
    swapfile_swappiness: "{{ swapfile_swappiness_value|default(30) }}"

- name: check for swapfile
  stat:
    path: "{{ swapfile_path }}"
  register: swapfile

- name: write swapfile
  command: |
    dd if=/dev/zero of={{ swapfile_path }} if=/dev/zero count={{ swapfile_size }} bs=1M
  environment:
    PATH: "{{ (ansible_env|default({})).PATH|default('') }}:/usr/local/sbin:/usr/sbin:/sbin"
  register: write_swapfile
  when: not swapfile.stat.exists

- name: set swapfile permissions
  file: path={{ swapfile_path }} mode=600

- name: create swapfile
  command: mkswap {{ swapfile_path }}
  environment:
    PATH: "{{ (ansible_env|default({})).PATH|default('') }}:/usr/local/sbin:/usr/sbin:/sbin"
  register: swapfile_created
  when: write_swapfile.changed

- name: enable swapfile
  command: swapon {{ swapfile_path }}
  environment:
    PATH: "{{ (ansible_env|default({})).PATH|default('') }}:/usr/local/sbin:/usr/sbin:/sbin"
  when: swapfile_created.changed

- name: Add swapfile to /etc/fstab
  lineinfile: dest=/etc/fstab line="{{ swapfile_path }}   none    swap    sw    0   0" state=present
  when: swapfile_created.changed

- name: Configure vm.swappiness
  lineinfile: dest=/etc/sysctl.conf line="vm.swappiness = {{ swapfile_swappiness }}" regexp="^vm.swappiness[\s]?=" state=present
  notify: sysctl reload
  when: swapfile_swappiness != False

