---
# needed to get the undercloud in our inventory
- hosts: localhost
  connection: local
  gather_facts: false
  vars_prompt:
    - name: "flavor"
      prompt: "Base OS Variant (centos|rhel)"
      default: "centos"

  tasks:
  - include: tasks/undercloud-provision-centos.yml
    when: flavor == "centos"
  - include: tasks/undercloud-provision-rhel.yml
    when: flavor == "rhel"

# setup repos and deploy basic undercloud
- hosts: undercloud
  tags:
    - overcloud
  gather_facts: true
  vars_prompt:
    - name: "version"
      prompt: "Openstack Release version for repos (current|passed-ci|newton|ocata)"
      default: "current"
    - name: "inventory_file_source"
      prompt: "Overcloud node inventory file"
      default: "nodes.json"

  tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/default.yml"
    - include: tasks/overcloud-setup-images-{{ version }}.yml
      when: ansible_distribution == "CentOS"
    - include: tasks/overcloud-setup-images-rhel.yml
      when: ansible_distribution == "RedHat"
    - include: tasks/overcloud-setup-load-inventory.yml
