---
# setup undercloud vm
- hosts: localhost
  connection: local
  gather_facts: false
  tags:
    - undercloud
  vars_prompt:
    - name: "flavor"
      prompt: "Base OS Variant (centos|rhel)"
      default: "centos"
  roles:
      - undercloud-provision

# do the initial yum update -y && reboot
- hosts: undercloud
  tags:
    - undercloud
  gather_facts: true
  vars_prompt:
    - name: "version"
      prompt: "Version to deploy (current|consistent|current-tripleo|pike|ocata|newton|rhel)?"
      default: "current-tripleo"
  tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - "vars/os/{{ ansible_distribution }}.yml"
        - "vars/default.yml"
    - include_role:
        name: undercloud-host-setup

