---
- name: launch undercloud
  os_server:
    auth:
      auth_url: "{{ os_auth_url }}"
      username: "{{ os_username }}"
      password: "{{ os_password }}"
      project_name: "{{ os_tenant_name }}"
    name: "{{ undercloud_name }}"
    state: present
    flavor: "{{ undercloud_flavor }}"
    image: "{{ glance_centos_image }}"
    key_name: "default"
    nics: "{{ undercloud_nics }}"
    floating_ips: "{{ undercloud_floating_ips }}"
  register: undercloud
  tags:
    - provision

- include: tasks/undercloud-provision.yml
