---
- name: build images
  shell: |
      source ~/stackrc
      export NODE_DIST="{{overcloud_flavor}}"
      export USE_DELOREAN_TRUNK=1
      export DELOREAN_TRUNK_REPO="$(grep baseurl /etc/yum.repos.d/delorean.repo | cut -d= -f2)"
      export DELOREAN_REPO_FILE="delorean.repo"
      export DIB_YUM_REPO_CONF=/etc/yum.repos.d/delorean*
      export DIB_YUM_REPO_CONF="$DIB_YUM_REPO_CONF /etc/yum.repos.d/CentOS-Ceph-Jewel.repo"
      export OS_YAML="/usr/share/openstack-tripleo-common/image-yaml/overcloud-images-centos7.yaml"
      openstack overcloud image build --config-file /usr/share/openstack-tripleo-common/image-yaml/overcloud-images.yaml --config-file $OS_YAML
  tags:
    - setup
  become_user: "{{ undercloud_user }}"
