---
#- include_tasks: ceph.yml
#  tags: undercloud-repo-setup
#  when: version != "rhel"

- include_tasks: "{{ version }}.yml"
  tags: undercloud-repo-setup
  when: version == "rhel" or version == "rhos-release"

- include_tasks: tripleo-repos.yml
  tags: undercloud-repo-setup
  when:
   - version != "rhel"
   - version != "rhos-release"

- include_tasks: update.yml
  tags: undercloud-repo-setup
  when: update_undercloud|bool
