---
- name: reboot server
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  become: true
  ignore_errors: true

- name: wait for server to start
  local_action: wait_for host={{ ansible_host }} search_regex=OpenSSH port=22 timeout=300 delay=10
  become: false
